version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    hostname: app
    command: sh -c "alembic upgrade head && python main.py"
    volumes:
      - ./src:/app
    env_file:
      - .envfile
    ports:
      - '0.0.0.0:8000:8000'
    depends_on:
      - db
    restart: always
    container_name: app
    logging:
      driver: "json-file"

  db:
    image: postgres:12-alpine
    env_file:
      - .envfile
    volumes:
    - db-data:/var/lib/postgresql/data
    container_name: db
    expose:
      - '5432'
    restart: unless-stopped
    logging:
      driver: 'json-file'

  redis:
    image: redis:alpine
    working_dir: /data
    expose:
      - '6379'
    volumes:
      - /data:/data
    container_name: redis
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '1'

volumes:
  db-data:
  redis: