"""Create schedule, schedule_cell, meeting, user tables

Revision ID: 14baa03ba2da
Revises: 
Create Date: 2022-03-08 13:20:40.443612

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '14baa03ba2da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=1024), nullable=True),
    sa.Column('role', sa.String(length=9), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('schedule_attendee',
    sa.Column('attendee_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('schedule_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['attendee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.PrimaryKeyConstraint('attendee_id', 'schedule_id')
    )
    op.create_table('schedule_cell',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('datetime_start', sa.DateTime(), nullable=True),
    sa.Column('datetime_end', sa.DateTime(), nullable=True),
    sa.Column('schedule_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meetings',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('welcome_message', sa.String(length=128), nullable=True),
    sa.Column('moderator_message', sa.String(length=128), nullable=False),
    sa.Column('record', sa.Boolean(), nullable=True),
    sa.Column('auto_start_recording', sa.Boolean(), nullable=True),
    sa.Column('allow_start_stop_recording', sa.Boolean(), nullable=True),
    sa.Column('webcams_only_for_moderator', sa.Boolean(), nullable=True),
    sa.Column('mute_on_start', sa.Boolean(), nullable=True),
    sa.Column('allow_mods_to_unmute_users', sa.Boolean(), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('datetime_start', sa.DateTime(), nullable=True),
    sa.Column('datetime_end', sa.DateTime(), nullable=True),
    sa.Column('schedule_cell_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_cell_id'], ['schedule_cell.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meetings')
    op.drop_table('schedule_cell')
    op.drop_table('schedule_attendee')
    op.drop_table('user')
    op.drop_table('schedule')
    # ### end Alembic commands ###
