"""schedule app

Revision ID: 0f7ea1d68fc0
Revises: e541ec33fc8b
Create Date: 2021-07-21 09:17:59.451360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f7ea1d68fc0'
down_revision = 'e541ec33fc8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
