"""updated Meeting.id

Revision ID: 8005dddb1ef3
Revises: a6ddb8e136f8
Create Date: 2021-07-09 17:32:24.239365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8005dddb1ef3'
down_revision = 'a6ddb8e136f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'meeting', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meeting', type_='unique')
    # ### end Alembic commands ###
