"""Meeting, Schedule, ScheduleCell tables added

Revision ID: 86cd34fa749f
Revises: d137934b754b
Create Date: 2021-07-08 20:41:37.824101

"""
import ormar
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86cd34fa749f'
down_revision = 'd137934b754b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_cell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime_start', sa.DateTime(), nullable=False),
    sa.Column('datetime_end', sa.DateTime(), nullable=False),
    sa.Column('schedule', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['schedule'], ['schedule.id'], name='fk_schedule_cell_schedule_id_schedule'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('schedule', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['schedule'], ['schedule.id'], name='fk_schedules_users_schedule_schedule_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['user.id'], name='fk_schedules_users_user_user_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting',
    sa.Column('id', ormar.fields.sqlalchemy_uuid.CHAR(36), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('welcome_message', sa.String(length=128), nullable=False),
    sa.Column('moderator_message', sa.String(length=128), nullable=False),
    sa.Column('record', sa.Boolean(), nullable=True),
    sa.Column('auto_start_recording', sa.Boolean(), nullable=True),
    sa.Column('allow_start_stop_recording', sa.Boolean(), nullable=True),
    sa.Column('webcams_only_for_moderator', sa.Boolean(), nullable=True),
    sa.Column('mute_on_start', sa.Boolean(), nullable=True),
    sa.Column('allow_mods_to_unmute_users', sa.Boolean(), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('schedule_cell', sa.Integer(), nullable=True),
    sa.Column('datetime_start', sa.DateTime(), nullable=False),
    sa.Column('datetime_end', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_cell'], ['schedule_cell.id'], name='fk_meeting_schedule_cell_id_schedule_cell'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting')
    op.drop_table('schedules_users')
    op.drop_table('schedule_cell')
    op.drop_table('schedule')
    # ### end Alembic commands ###
