"""uuid format to Meeting.id

Revision ID: e541ec33fc8b
Revises: 8005dddb1ef3
Create Date: 2021-07-11 11:26:54.447335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e541ec33fc8b'
down_revision = '8005dddb1ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
