FROM python:3.9-alpine

COPY ../requirements.txt /app/requirements.txt
COPY tests/requirements.txt /app/tests/requirements.txt

WORKDIR /app/

COPY .. .

RUN apk add gcc g++ libffi-dev

RUN python -m pip --no-cache-dir install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install -r tests/requirements.txt
